packaging_format = 2

id = "peertube"
name = "PeerTube"
description.en = "Federated video streaming platform using P2P directly in the web browser"
description.fr = "Plateforme fédéralisé de diffusion vidéo par P2P directement dans le navigateur"

version = "5.1.0~ynh1"

maintainers = ["yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://joinpeertube.org/fr"
demo = "http://peertube.cpy.re"
admindoc = "https://docs.joinpeertube.org"
code = "https://github.com/Chocobozzz/PeerTube"

[integration]
yunohost = ">= 11.1.20"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        url = "https://github.com/Chocobozzz/PeerTube/releases/download/v5.1.0/peertube-v5.1.0.tar.xz"
        sha256 = "5254562020e27a4d11364e4b6b348e0ce073d36b9a7a1c8d9e1e2d5248d77552"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]
    main.default = 8095
    rtmp.default = 1935
    rtmp.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["storage"]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "prosody ffmpeg postgresql postgresql-contrib openssl g++ mailutils apt-transport-https"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
