test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.9bf92ff6.name = "Upgrade from 4.2.2"