test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.8a8d9be.name = "5.2.1"
